name: social_media
description: "Social Media Project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  responsive_sizer: ^3.3.1
  easy_localization: ^3.0.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  http: ^1.1.0
  get_it: ^8.0.0
  http_parser: ^4.0.2
  connectivity_plus: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  package_info_plus:
  flutter_exit_app: ^1.1.4
  intl_phone_number_input: ^0.7.4
  cached_network_image: ^3.3.0
  page_view_dot_indicator: ^2.3.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  story_time: ^1.0.6
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Glory
      fonts:
        - asset: assets/fonts/Glory-Light.ttf
          weight: 300
        - asset: assets/fonts/Glory-Regular.ttf
          weight: 400
        - asset: assets/fonts/Glory-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Glory-Bold.ttf
          weight: 700
